project:
  type: website
  output-dir: docs

website:
  title: "Isaac Bain"
  navbar:
    right:
      - about.qmd
      - blog.qmd
      - icon: github
        href: https://github.com/isaacbain
      - icon: linkedin
        href: https://www.linkedin.com/in/isaac-bain-4a0227172
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

